name: VStarStack

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pylint
          python -m pip install pytest
          python -m pip install -r requirements.txt
      - name: Lint with pylint
        run: |
          pylint --rcfile=pylintrc --fail-under=9 src/
      - name: Build & Install
        run: |
          python setup.py build
          python setup.py install
      - name: Test that tools launches
        run: |
          vstarstack
      - name: Test with pytest
        run: |
          pytest --cov-fail-under=25 --cov=vstarstack tests/
